name: Sync ORCID publications
on:
  schedule:
    - cron: "0 5 * * 1"   # chaque lundi 05:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Fetch ORCID works
        env:
          ORCID_ID: ${{ vars.ORCID_ID }}
        run: |
          if [ -z "$ORCID_ID" ]; then
            echo "Configurez un Repository Variable ORCID_ID dans Settings > Secrets and variables > Actions > Variables"
            exit 1
          fi
          curl -sH "Accept: application/json" "https://pub.orcid.org/v3.0/${ORCID_ID}/works" \
            | jq '[.group[] | .["work-summary"][0] as $w | {title: ($w.title.title.value // "Sans titre"), year: ($w["publication-date"].year.value // ""), journal: ($w["journal-title"].value // ""), url: ($w.url.value // ((.["external-ids"]["external-id"] // []) | map(select(.["external-id-type"]|ascii_downcase=="doi")) | .[0]["external-id-value"]? | if . then "https://doi.org/"+. else null end))}]' \
            > publications.json
      - name: Commit publications.json
        run: |
          if [ -n "$(git status --porcelain publications.json)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add publications.json
            git commit -m "Update publications.json from ORCID"
            git push
          else
            echo "No changes."
          fi
