name: Update sitemap lastmod
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update lastmod
        run: |
          d=$(date -u +"%Y-%m-%d")
          sed -i "s#<lastmod>.*</lastmod>#<lastmod>${d}</lastmod>#g" sitemap.xml
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add sitemap.xml
            git commit -m "chore: sitemap lastmod ${d}"
            git push
          else
            echo "No changes."
          fi
